type FollowingProfile = {
    index: number
    handle: string
    username: string
    scrollHeight: number
    description?: string
}
type ProfileData = Omit<FollowingProfile, 'index'>
interface ProfileContainer extends HTMLElement {
    readonly dataset: {
        testid: 'cellInnerDiv'
    }
}
interface ProfileInner extends HTMLElement {
    readonly dataset: {
        testid: 'UserCell'
    }
}
interface Window {
    __INITIAL_STATE__: any
}
interface FollowingContainer extends HTMLElement {
    readonly ariaLabel: 'Timeline: Following'
}
type From = 'content' | 'background' | 'popup'
type To = 'content' | 'background' | 'popup'
type RequestType = 'userData' | 'start'
type Data = string | unknown
type ExtMessage<
    From extends 'content' | 'popup' | 'background',
    To extends 'background' | 'content' | 'popup',
    RequestType extends From extends 'content'
        ? 'userData' | 'start'
        : From extends 'background'
        ? 'start' | 'userData'
        : From extends 'popup'
        ? 'userData'
        : never = never,
    Data extends To extends 'content'
        ? string | undefined
        : To extends 'background'
        ? string | unknown
        : To extends 'popup'
        ? string
        : never = never
> = {
    from: From
    to: To
    type: RequestType
    data?: Data
}
type BGtoCSMessage =
    | ExtMessage<'background', 'content', 'start', never>
    | ExtMessage<'background', 'content', 'userData', string>
type BGtoPopupMessage = ExtMessage<'background', 'popup', 'userData', string>
type CStoBGMessage =
    | ExtMessage<'content', 'background', 'start'>
    | ExtMessage<'content', 'background', 'userData', string>
type CStoPopupMessage = ExtMessage<'content', 'popup', 'userData', string>
type PopupToBGMessage = ExtMessage<'popup', 'background', 'userData', any>
type WindowMessage = {
    source: {
        window: WindowProxy
    }
    data: any
}

// Generated by https://quicktype.io

interface TwitterUserData {
    can_dm: boolean
    can_media_tag: boolean
    default_profile: boolean
    default_profile_image: boolean
    description: string
    entities: Entities
    fast_followers_count: number
    favourites_count: number
    followers_count: number
    friends_count: number
    has_custom_timelines: boolean
    is_translator: boolean
    listed_count: number
    location: string
    media_count: number
    name: string
    needs_phone_verification: boolean
    normal_followers_count: number
    pinned_tweet_ids_str: any[]
    possibly_sensitive: boolean
    profile_banner_url: string
    profile_image_url_https: string
    profile_interstitial_type: string
    screen_name: string
    statuses_count: number
    translator_type: string
    verified: boolean
    want_retweets: boolean
    withheld_in_countries: any[]
    id_str: string
    is_profile_translatable: boolean
    profile_image_shape: string
    is_blue_verified: boolean
    birthdate: Birthdate
    has_graduated_access: boolean
    created_at: string
    blocked_by: boolean
    muting: boolean
    blocking: boolean
}

interface Birthdate {
    day: number
    month: number
    year: number
    visibility: string
    year_visibility: string
}

interface Entities {
    description: Description
}

interface Description {
    urls: any[]
}
